## Deliverable 2. Create a Customer Travel Destinations Map.

In [2]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [8]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Hermanus,ZA,-34.4187,19.2345,71.80,84,96,6.53,overcast clouds
1,1,Busselton,AU,-33.6500,115.3333,57.09,69,0,14.09,clear sky
2,2,Beringovskiy,RU,63.0500,179.3167,-25.89,95,23,7.56,few clouds
3,3,Saint-Georges,GD,12.0564,-61.7485,83.88,70,75,20.71,broken clouds
4,4,Bambous Virieux,MU,-20.3428,57.7575,78.22,81,47,7.52,scattered clouds

In [9]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [20]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
3,3,Saint-Georges,GD,12.0564,-61.7485,83.88,70,75,20.71,broken clouds
4,4,Bambous Virieux,MU,-20.3428,57.7575,78.22,81,47,7.52,scattered clouds
5,5,Jacareacanga,BR,-6.2222,-57.7528,83.80,83,91,2.93,overcast clouds
6,6,Kununurra,AU,-15.7667,128.7333,78.78,94,13,2.30,few clouds
7,7,Lompoc,US,34.6391,-120.4579,80.08,34,10,2.48,clear sky
9,9,Quatre Cocos,MU,-20.2078,57.7625,80.71,81,61,8.12,light rain
10,10,Puerto Ayora,EC,-0.7393,-90.3518,79.56,85,87,3.00,overcast clouds
11,11,Cayenne,GF,4.9333,-52.3333,82.44,90,75,10.36,broken clouds
18,18,Rikitea,PF,-23.1203,-134.9692,78.71,72,38,16.31,scattered clouds
26,26,Grand Gaube,MU,-20.0064,57.6608,81.00,76,84,1.99,broken clouds

In [21]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                211
City                   211
Country                208
Lat                    211
Lng                    211
Max Temp               211
Humidity               211
Cloudiness             211
Wind Speed             211
Current Description    211
dtype: int64

In [19]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)].dropna()
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
3,3,Saint-Georges,GD,12.0564,-61.7485,83.88,70,75,20.71,broken clouds
4,4,Bambous Virieux,MU,-20.3428,57.7575,78.22,81,47,7.52,scattered clouds
5,5,Jacareacanga,BR,-6.2222,-57.7528,83.80,83,91,2.93,overcast clouds
6,6,Kununurra,AU,-15.7667,128.7333,78.78,94,13,2.30,few clouds
7,7,Lompoc,US,34.6391,-120.4579,80.08,34,10,2.48,clear sky
9,9,Quatre Cocos,MU,-20.2078,57.7625,80.71,81,61,8.12,light rain
10,10,Puerto Ayora,EC,-0.7393,-90.3518,79.56,85,87,3.00,overcast clouds
11,11,Cayenne,GF,4.9333,-52.3333,82.44,90,75,10.36,broken clouds
18,18,Rikitea,PF,-23.1203,-134.9692,78.71,72,38,16.31,scattered clouds
26,26,Grand Gaube,MU,-20.0064,57.6608,81.00,76,84,1.99,broken clouds

In [23]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,Saint-Georges,GD,83.88,broken clouds,12.0564,-61.7485,
4,Bambous Virieux,MU,78.22,scattered clouds,-20.3428,57.7575,
5,Jacareacanga,BR,83.80,overcast clouds,-6.2222,-57.7528,
6,Kununurra,AU,78.78,few clouds,-15.7667,128.7333,
7,Lompoc,US,80.08,clear sky,34.6391,-120.4579,
9,Quatre Cocos,MU,80.71,light rain,-20.2078,57.7625,
10,Puerto Ayora,EC,79.56,overcast clouds,-0.7393,-90.3518,
11,Cayenne,GF,82.44,broken clouds,4.9333,-52.3333,
18,Rikitea,PF,78.71,scattered clouds,-23.1203,-134.9692,
26,Grand Gaube,MU,81.00,broken clouds,-20.0064,57.6608,

In [27]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [38]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df[hotel_df["Hotel Name"]!= '']
clean_hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,Saint-Georges,GD,83.88,broken clouds,12.0564,-61.7485,Radisson Grenada Beach Resort
4,Bambous Virieux,MU,78.22,scattered clouds,-20.3428,57.7575,Casa Tia Villa
5,Jacareacanga,BR,83.80,overcast clouds,-6.2222,-57.7528,Casa do Ian😎
6,Kununurra,AU,78.78,few clouds,-15.7667,128.7333,Hotel Kununurra
7,Lompoc,US,80.08,clear sky,34.6391,-120.4579,"Holiday Inn Express Lompoc, an IHG Hotel"
9,Quatre Cocos,MU,80.71,light rain,-20.2078,57.7625,Sunrise Attitude Hotel
10,Puerto Ayora,EC,79.56,overcast clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel
11,Cayenne,GF,82.44,broken clouds,4.9333,-52.3333,Hôtel Le Dronmi
18,Rikitea,PF,78.71,scattered clouds,-23.1203,-134.9692,People ThankYou
26,Grand Gaube,MU,81.00,broken clouds,-20.0064,57.6608,Veranda Paul et Virginie Hotel & Spa

In [40]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [41]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [42]:
# 11a. Add a marker layer for each city to the map. 
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig = gmaps.figure()
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))